ecommerce/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.index, name = 'index'),
    path('category',views.category_list, name = 'category'),
    path('products',views.product_list, name = 'products'),
    path('product_details/<slug>', views.product_details, name = 'product-details'),
    path('category_products/<slug>', views.category_products, name = 'category-products'),
    path('contat', views.contact, name = 'contact'),


    #cart urls
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
]

estore/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('ecommerce.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/models.py
from shutil import register_unpack_format
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = RichTextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)    
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.name

class ProductImage(models.Model):
    product = models.ForeignKey(Product, default= None, on_delete=models.PROTECT)
    images = models.ImageField(upload_to='photos/products',default=None)

    

ecommerce/views.py
from email.headerregistry import DateHeader
from unicodedata import category
from django.shortcuts import render,redirect
from .models import *

from django.contrib.auth.decorators import login_required
from cart.cart import Cart

from django.core.mail import send_mail
from django.db.models import Q

# Create your views here.
def index(request):
    if request.GET.get('search'):
        search = request.GET.get('search')
        search = search.lower()
        prod = Product.objects.filter(
            Q(name__icontains=search) |
            Q(description__icontains=search) |
            Q(category__name__icontains=search)
        )

        data = {
            'productData': prod,

        }
        return render(request, 'pages/product_list.html', data)

    else:
        cat = Category.objects.all()
        prod = Product.objects.all()
        data = {
            'categoryData': cat,
            'productData': prod,

        }

        return render(request, 'pages/index.html', data)


def category_list(request):
    cat = Category.objects.all()
    data = {
        'categoryData': cat
    }
    return render(request, 'pages/category_list.html',data)

def product_list(request):
    prod = Product.objects.all()
    data = {
        'productData': prod
    }
    return render(request, 'pages/product_list.html',data)

def product_details(request,slug):
    prod = Product.objects.get(slug=slug)
    data = {
        'productData': prod
    }
    return render(request, 'pages/product_details.html',data)

def category_products(request,slug):
        cat = Category.objects.get(slug=slug)
        data = {
        'categoryData': cat
        }
        return render(request, 'pages/category_products.html',data)

def contact(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        send_mail(subject, message, email,['ishwarkhadka@kcc.edu.np'])
        return redirect('contact')
    else:
        return render(request, 'pages/contact.html')
    


#Add to cart 
@login_required(login_url="/users/login")
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    redirect_back = request.META.get('HTTP_REFERER')
    return redirect(redirect_back)


@login_required(login_url="/users/login")
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def item_increment(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def item_decrement(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def cart_detail(request):
    return render(request, 'pages/cart_detail.html')

templates/layouts/footer.html
<!--
Footer
-->
{% load static %}
<footer class="footer">
    <div class="row-fluid">
    <div class="span2">
    <h5>Your Account</h5>
    <a href="#">YOUR ACCOUNT</a><br>
    <a href="#">PERSONAL INFORMATION</a><br>
    <a href="#">ADDRESSES</a><br>
    <a href="#">DISCOUNT</a><br>
    <a href="#">ORDER HISTORY</a><br>
     </div>
    <div class="span2">
    <h5>Iinformation</h5>
    <a href="contact.html">CONTACT</a><br>
    <a href="#">SITEMAP</a><br>
    <a href="#">LEGAL NOTICE</a><br>
    <a href="#">TERMS AND CONDITIONS</a><br>
    <a href="#">ABOUT US</a><br>
     </div>
    <div class="span2">
    <h5>Our Offer</h5>
    <a href="#">NEW PRODUCTS</a> <br>
    <a href="#">TOP SELLERS</a><br>
    <a href="#">SPECIALS</a><br>
    <a href="#">MANUFACTURERS</a><br>
    <a href="#">SUPPLIERS</a> <br/>
     </div>
     <div class="span6">
    <h5>The standard chunk of Lorem</h5>
    The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for
     those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et 
     Malorum" by Cicero are also reproduced in their exact original form, 
    accompanied by English versions from the 1914 translation by H. Rackham.
     </div>
     </div>
</footer>
    </div><!-- /container -->
    
    <div class="copyright">
    <div class="container">
        <p class="pull-right">
            <a href="#"><img src="assets/img/maestro.png" alt="payment"></a>
            <a href="#"><img src="assets/img/mc.png" alt="payment"></a>
            <a href="#"><img src="assets/img/pp.png" alt="payment"></a>
            <a href="#"><img src="assets/img/visa.png" alt="payment"></a>
            <a href="#"><img src="assets/img/disc.png" alt="payment"></a>
        </p>
        <span>Copyright &copy; 2013<br> bootstrap ecommerce shopping template</span>
    </div>
    </div>
    <a href="#" class="gotop"><i class="icon-double-angle-up"></i></a>
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'assets/js/jquery.js' %}"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery.easing-1.3.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery.scrollTo-1.4.3.1-min.js' %}"></script>
        <script src="{% static 'assets/js/shop.js' %}"></script>
      </body>
    </html>

templates/layouts/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Twitter Bootstrap shopping cart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap styles -->
    <link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet"/>
    <!-- Customize styles -->
    <link href="{% static 'style.css' %}" rel="stylesheet"/>
    <!-- font awesome styles -->
	<link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
		<!--[if IE 7]>
			<link href="css/font-awesome-ie7.min.css" rel="stylesheet">
		<![endif]-->

		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

	<!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'assets/ico/favicon.ico' %}">
  </head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="topNav">
      <div class="container">
        <div class="alignR">
          
          <a class="active" href="index.html"> <span class="icon-home"></span> Home</a> 
          <a href="#"><span class="icon-user"></span> My Account</a> 
          <a href="{% url 'cart_detail' %}"><span class="icon-shopping-cart"></span> Cart</a>
        </div>
      </div>
    </div>
  </div>
  
  <!--
  Lower Header Section 
  -->
  <div class="container">
  <div id="gototop"> </div>
  <header id="header">
  <div class="row">
    <div class="span4">
    <h1>
    <a class="logo" href="index.html"><span>Estore</span> 
      <img src="" alt="E-store">
    </a>
    </h1>
    </div>
  
    
  </div>
  </header>
  
  <!--
  Navigation Bar Section 
  -->
  <div class="navbar">
      <div class="navbar-inner">
      <div class="container">
        <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </a>
        <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><a href="{% url 'index' %}">Home	</a></li>
          <li class = ""><a href="{% url 'category' %}">Category</a></li>
          <li class = ""><a href="{% url 'products'%}">Products</a></li>
          <li class = ""><a href="{% url 'contact' %}">Contact</a></li>

        </ul>
        
        
        </div>
      </div>
      </div>
    </div>
  

templates/master/master.html
{% include 'layouts/header.html' %}

{% block content %}

{% endblock %}

{% include 'layouts/footer.html' %}

templates/pages/cart_detail.html
{% extends 'master/master.html' %}
{% load cart_tag %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="span12">
                <ul class="breadcrumb">
                    <li><a href="{% url 'index' %}">Home</a> <span class="divider">/</span></li>
                    <li class="active">Check Out</li>
                </ul>
                <div class="well well-small">
                    <h1>Check Out <small class="pull-right"></small></h1>
                    <hr class="soften"/>

                    <table class="table table-bordered table-condensed">
                        <thead>
                        <tr>
                            <th>Image</th>
                            <th>Product name</th>
                            <th>Price</th>
                            <th>Qty</th>
                            <th>Total</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for key,value in request.session.cart.items %}
                            <tr>
                                <td>
                                    <img src="{{ value.image }}" width="30" alt="">
                                </td>
                                <td>
                                    {{ value.name }}
                                </td>
                                <td>{{ value.price }}</td>
                                <td>
                                    <a href="{% url 'item_increment' value.product_id %}" class="btn btn-primary">+</a>
                                    {{ value.quantity }}
                                    <a href="{% url 'item_decrement' value.product_id %}" class="btn btn-danger">-</a>
                                </td>
                                <td>
                                    {{ value.price|multiply:value.quantity }}
                                </td>
                                <td>
                                    <a href="{% url 'item_clear' value.product_id %}" class="btn btn-warning">Remove</a>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="5">
                                <a href="{% url 'cart_clear' %}"
                                   onclick="return confirm('are you sure?')"
                                   class="btn btn-danger">Clear Cart</a>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                    <br/>


                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/pages/category_list.html
{% extends 'master/master.html' %}

{% block content %}

    <div class="well well-small">
        {% for category in categoryData %}
            <h3>{{ category.name }} </h3>
            <ul class="thumbnails">
            {% for product in category.product_set.all %}


      <li class="span4">
        <div class="thumbnail">
        <a href="" class="overlay"></a>
        <a class="zoomTool" href="" title="add to cart"><span class="icon-search"></span> QUICK VIEW</a>
        <a href="">
                    {% if product.image %}
                    <img src="{{ product.image.url }}" alt="" style="width: 100%;height: 200px;">
                    {% endif %}
                </a>
        <div class="caption cntr">
          <p>{{ product.name }}</p>
          <p><strong> Rs: {{ product.price }}</strong></p>
          <h4><a class="shopBtn" href="#" title="add to cart"> Add to cart </a></h4>
          <div class="actionList">
            <a class="pull-left" href="#">Add to Wish List </a>
            <a class="pull-left" href="#"> Add to Compare </a>
          </div>
          <br class="clr">
        </div>
        </div>
      </li>

            {% endfor %}

      </ul>


            <hr>

        {% endfor %}


    </div>
    </div>


{% endblock %}

templates/pages/category_products.html
{% extends 'master/master.html' %}

{% block content %}

    <div class="well well-small">
            <h3>{{ categoryData.name }} </h3>

            <ul class="thumbnails">
            {% for product in categoryData.product_set.all %}


      <li class="span4">
        <div class="thumbnail">
        <a href="" class="overlay"></a>
        <a class="zoomTool" href="" title="add to cart"><span class="icon-search"></span> QUICK VIEW</a>
        <a href="">
                    {% if product.image %}
                    <img src="{{ product.image.url }}" alt="" style="width: 100%;height: 200px;">
                    {% endif %}
                </a>
        <div class="caption cntr">
          <p>{{ product.name }}</p>
          <p><strong> Rs: {{ product.price }}</strong></p>
          <h4><a class="shopBtn" href="#" title="add to cart"> Add to cart </a></h4>
          <div class="actionList">
            <a class="pull-left" href="#">Add to Wish List </a>
            <a class="pull-left" href="#"> Add to Compare </a>
          </div>
          <br class="clr">
        </div>
        </div>
      </li>

            {% endfor %}

      </ul>


            <hr>



    </div>
    </div>


{% endblock %}

templates/pages/contact.html
{% extends 'master/master.html' %}
{% block content %}
    <div class="container">
        <div class="well well-small">
            <h1>Visit us</h1>
            <hr class="soften"/>
            <div class="row-fluid">
                <div class="span8 relative">
                    <div class="absoluteBlk">
                        <div class="well wellsmall">
                            <h4>Contact Details</h4>
                            <h5>
                                2601 Mission St.<br/>
                                San Francisco, CA 94110<br/><br/>

                                info@mysite.com<br/>
                                ﻿Tel 123-456-6780<br/>
                                Fax 123-456-5679<br/>
                                web:wwwmysitedomain.com
                            </h5>
                        </div>
                    </div>
                </div>

                <div class="span4">
                    <h4>Email Us</h4>
                    <form class="form-horizontal" method="post">
                        {% csrf_token %}

                        <fieldset>
                            <div class="control-group">

                                <input type="text" name="email" required placeholder="email" class="input-xlarge"/>

                            </div>
                            <div class="control-group">

                                <input type="text" name="subject" required placeholder="subject" class="input-xlarge"/>

                            </div>
                            <div class="control-group">
                                <textarea rows="3" name="message" required id="textarea" class="input-xlarge"></textarea>

                            </div>

                            <button class="shopBtn" type="submit">Send email</button>

                        </fieldset>
                    </form>
                </div>
            </div>


        </div>
    </div>
</div>

{% endblock %}

templates/pages/product_details.html
{% extends 'master/master.html' %}
{% block content %}
    <div class="span12">
        <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a> <span class="divider">/</span></li>
            <li><a href="#">Items</a> <span class="divider">/</span></li>
            <li class="active">Preview</li>
        </ul>
        <div class="well well-small">
            <div class="row-fluid">
                <div class="span5">
                    <div id="myCarousel" class="carousel slide cntr">
                        <div class="carousel-inner">
                            <div class="item active">
                                {% if productData.image %}
                                    <a href="#"> <img src="{{ productData.image.url }}" alt="" style="width:100%;height:400px" ></a>
                                {% endif %}
                            </div>
                            {% for pImage in  productData.productimage_set.all %}
                                <div class="item">
                                    <a href="#"> <img src="{{ pImage.images.url }}" alt="" style="width:100%;height:400px" height="500px"></a>
                                </div>
                            {% endfor %}


                        </div>
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
                    </div>
                </div>
                <div class="span7">
                    <h3>{{ productData.name }}</h3>
                    <hr class="soft"/>

                    <form class="form-horizontal qtyFrm">
                        <div class="control-group">
                            <label class="control-label"><span>Rs: {{ productData.price }}</span></label>
                            <div class="controls">
                                <input type="number" class="span6" placeholder="Qty.">
                            </div>
                        </div>
                        <h4>100 items in stock</h4>
                        <p>Nowadays the lingerie industry is one of the most successful business spheres.
                            Nowadays the lingerie industry is one of ...
                        <p>
                            <button type="submit" class="shopBtn"><span class=" icon-shopping-cart"></span> Add to cart
                            </button>
                    </form>
                </div>
            </div>

            <p>
                {{ productData.description |safe }}
            </p>


        </div>
    </div>
    </div> <!-- Body wrapper -->
{% endblock %}

templates/pages/product_list.html
{% extends 'master/master.html' %} 

{% block content %}
<div class="well well-small">
	<h3>Our Products </h3>

		<div class="row-fluid">
		  <ul class="thumbnails">
            {% for product in productData%}
			<li class="span4">
			  <div class="thumbnail">
				<a href="" class="overlay"></a>
				<a class="zoomTool" href="{% url 'product-details' product.slug%}" title="add to cart"><span class="icon-search"></span> QUICK VIEW</a>
				{% if product.image%}
                <a href=""><img src="{{ product.image.url }}" alt="" style="width:100%;height:300px;"></a>
                {% endif %}
				<div class="caption cntr">
					<p>{{ product.name}}</p>
					<p><strong> ${{ product.price }}</strong></p>
					<h4><a class="shopBtn" href="{% url 'cart_add' product.id %}" title="add to cart"> Add to cart </a></h4>
					<div class="actionList">
						<a class="pull-left" href="#">Add to Wish List </a> 
						<a class="pull-left" href="#"> Add to Compare </a>
					</div> 
					<br class="clr">
				</div>
			  </div>
			</li>
			{% endfor %}
		  </ul>
		</div>
		
	
	</div>
</div>
{% endblock %}